C======================================================================
C     MODULE MULTALL_DATA
C     Replaces all COMMON blocks from commall-open-21.3
C     ID, JD, KD are runtime variables (not PARAMETERs)
C     All arrays using ID/JD/KD are ALLOCATABLE
C======================================================================
      MODULE MULTALL_DATA
      IMPLICIT NONE
      SAVE
C
C --- Fixed PARAMETERs (not grid-dependent) ---
C
      INTEGER, PARAMETER :: NRS = 21
      INTEGER, PARAMETER :: IG1 = 32, JG1 = 1000, KG1 = 41
      INTEGER, PARAMETER :: IG2 = 25, JG2 = 500, KG2 = 21
      INTEGER, PARAMETER :: JG3 = 100, NCWL = 100, NBLED = 25
      INTEGER, PARAMETER :: ITB = 150, JTB = 150
C
C --- Runtime dimension variables ---
C     MAXKI = MAX(ID, KD), set by ALLOC_MULTALL_DATA
C
      INTEGER :: MAXKI = 82
      INTEGER :: ID = 64
      INTEGER :: JD = 2500
      INTEGER :: KD = 82
C
C --- Allocation tracking ---
C
      INTEGER :: IM_ALLOC = 0, JM_ALLOC = 0
      INTEGER :: KM_ALLOC = 0, NROWS_ALLOC = 0
      INTEGER :: IALLOC_STATE = 0
C
C=== BKUTIL ===========================================================
C
      INTEGER :: NAME(18)
      REAL, ALLOCATABLE :: STORE(:,:,:)
      REAL, ALLOCATABLE :: TEMP1(:,:,:)
      REAL, ALLOCATABLE :: TEMP2(:,:,:)
      REAL, ALLOCATABLE :: TEMP3(:,:,:)
      REAL, ALLOCATABLE :: TEMP4(:,:,:)
      REAL, ALLOCATABLE :: STORE2(:,:,:)
      REAL, ALLOCATABLE :: SGEN(:,:,:)
      REAL :: PI, DEGRAD, RADDEG
C
C=== BKINTG ===========================================================
C
      INTEGER :: IM,JM,KM,IMM1,JMM1,KMM1,IMM2,JMM2,KMM2
      INTEGER :: IN_VTAN,INSURF,NOSECT,NSECS_IN,IN_VR
      INTEGER :: NSTEPS_MAX,NSTEP,ISMTH,JLEP1,IPOUT,ITIMST
      INTEGER :: IF_RESTART,NSTART,IMID,KMID,IBOUND
      INTEGER :: IOUT(20),NOUT(5)
      INTEGER, ALLOCATABLE :: KOUT(:)
      INTEGER, ALLOCATABLE :: JLE(:),JTE(:)
      INTEGER :: IFSHROUD,IFCOOL,IFBLEED,KIN,IFPRINT,IFEND
      INTEGER :: NSFEXIT,NSECS_ROW,IN_PRESS,IF_WAVE
      INTEGER, ALLOCATABLE :: INDLETE(:)
C
C=== BKGEOM ===========================================================
C
      REAL, ALLOCATABLE :: X(:,:), R(:,:)
      REAL, ALLOCATABLE :: RSURF(:,:), SMERID(:,:)
      REAL, ALLOCATABLE :: XSURF(:,:), DS(:,:)
      REAL, ALLOCATABLE :: RAVG_CELL(:,:)
      REAL, ALLOCATABLE :: RCYL(:)
      REAL, ALLOCATABLE :: DR(:,:)
      REAL, ALLOCATABLE :: THETA(:,:,:)
      REAL, ALLOCATABLE :: DX(:,:)
      REAL, ALLOCATABLE :: RT_UPP(:,:), RT_THICK(:,:)
      REAL, ALLOCATABLE :: RT_PITCH(:,:)
      REAL, ALLOCATABLE :: RTHETA(:,:,:)
      REAL, ALLOCATABLE :: BETAUP(:,:)
      REAL, ALLOCATABLE :: BETADWN1(:,:), BETADWN2(:,:)
      INTEGER :: IF_ANGLES(NRS), IF_REDESIGN(NRS)
      REAL, ALLOCATABLE :: FRACN_SPAN(:)
      REAL, ALLOCATABLE :: ANGL_UP(:),ANGL_DWN1(:),ANGL_DWN2(:)
C
C=== BKAREA ===========================================================
C
      REAL, ALLOCATABLE :: ABX(:,:,:)
      REAL, ALLOCATABLE :: ABR(:,:,:)
      REAL, ALLOCATABLE :: AQX(:,:,:)
      REAL, ALLOCATABLE :: AQR(:,:,:)
      REAL, ALLOCATABLE :: ASX(:,:,:)
      REAL, ALLOCATABLE :: ASR(:,:,:)
      REAL, ALLOCATABLE :: ABT(:,:), WRABT(:,:)
      REAL, ALLOCATABLE :: VOL(:,:,:)
      REAL, ALLOCATABLE :: VOLOR(:,:,:)
      REAL :: AQEXIT
      REAL, ALLOCATABLE :: AQTOT(:,:,:)
      REAL, ALLOCATABLE :: ABTOT(:,:,:)
C
C=== BKFLUX ===========================================================
C
      REAL, ALLOCATABLE :: XFLUX(:,:,:)
      REAL, ALLOCATABLE :: TFLUX(:,:,:)
      REAL, ALLOCATABLE :: RFLUX(:,:,:)
      REAL, ALLOCATABLE :: STEP(:,:,:)
      REAL, ALLOCATABLE :: BSTEP(:,:,:)
      REAL, ALLOCATABLE :: RSTEP(:,:,:)
      REAL, ALLOCATABLE :: SOURCE(:,:,:)
C
C=== BKFLOW ===========================================================
C
      REAL, ALLOCATABLE :: FLOWX(:,:,:)
      REAL, ALLOCATABLE :: FLOWR(:,:,:)
      REAL, ALLOCATABLE :: FLOWT(:,:,:)
      REAL :: SPECFLOW
C
C=== BKSEC ============================================================
C
      REAL, ALLOCATABLE :: VX(:,:,:)
      REAL, ALLOCATABLE :: VR(:,:,:)
      REAL, ALLOCATABLE :: VT(:,:,:)
      REAL, ALLOCATABLE :: PEFF(:,:,:)
      REAL, ALLOCATABLE :: T_STATIC(:,:,:)
      REAL, ALLOCATABLE :: WT(:,:,:)
C
C=== BKPRIM ===========================================================
C
      REAL, ALLOCATABLE :: RO(:,:,:)
      REAL, ALLOCATABLE :: P(:,:,:)
      REAL, ALLOCATABLE :: ROE(:,:,:)
      REAL, ALLOCATABLE :: ROVX(:,:,:)
      REAL, ALLOCATABLE :: ROVR(:,:,:)
      REAL, ALLOCATABLE :: ROVT(:,:,:)
      REAL, ALLOCATABLE :: RORVT(:,:,:)
      REAL, ALLOCATABLE :: HO(:,:,:)
      REAL, ALLOCATABLE :: ROSUB(:,:,:)
      REAL, ALLOCATABLE :: ROWT(:,:,:)
      REAL, ALLOCATABLE :: M_REL(:,:,:)
C
C=== BKFFLO ===========================================================
C
      INTEGER :: IN_FLOW
      REAL :: FLOWIN, RFLOW
      REAL, ALLOCATABLE :: FLOW(:)
C
C=== BKFRAC ===========================================================
C
      REAL, ALLOCATABLE :: FR(:), FR_IN(:)
      REAL, ALLOCATABLE :: FP(:)
      REAL, ALLOCATABLE :: FKU(:), FKD(:)
      REAL, ALLOCATABLE :: FU(:), FD(:)
      REAL, ALLOCATABLE :: BSSIN(:), BSCOS(:)
      REAL, ALLOCATABLE :: BRSIN(:), BRCOS(:)
      REAL, ALLOCATABLE :: FMUP(:,:), FMDN(:,:)
      REAL, ALLOCATABLE :: FACUP(:), FACDWN(:)
      REAL, ALLOCATABLE :: FSPAN(:), QSPAN(:)
C
C=== BKSMTH ===========================================================
C
      REAL :: SFTIN,SFT,SFT1,SFTH,SFXIN,SFX,SFX1,SFXH,SFXHM1
      REAL :: SFX14,SFX15,SFEX1,SFEXH
      REAL :: SFXB,SFXB1,SFXBH
      REAL :: FAC_4TH,RF,RFI,RFF,SFEXIT
      INTEGER :: NCHANGE, NRSMTH
      REAL :: RSMTH
      REAL :: F1,F2,F2EFF,F3,FP_XTRAP,FRACWAVE
C
C=== BKLOSS ===========================================================
C
      REAL :: FRACPB,FRACPW,REYNO,VISLAM,REL
      INTEGER :: ILOS,NLOS
      REAL :: CF,REL1
      REAL, ALLOCATABLE :: XFORCE(:,:,:)
      REAL, ALLOCATABLE :: RFORCE(:,:,:)
      REAL, ALLOCATABLE :: TFORCE(:,:,:)
      REAL, ALLOCATABLE :: QSOURCE(:,:,:)
      REAL, ALLOCATABLE :: VLAM(:), VTURB(:)
      REAL, ALLOCATABLE :: FKLAM(:,:), FKTURB(:,:)
      REAL, ALLOCATABLE :: FILAM(:,:), FITURB(:,:)
      REAL, ALLOCATABLE :: FIWAKE(:,:), FIUP(:,:)
      REAL :: FTRANS
      INTEGER, ALLOCATABLE :: JTRAN_I1(:), JTRAN_IM(:)
      INTEGER, ALLOCATABLE :: JTRAN_K1(:), JTRAN_KM(:)
      REAL :: XLLIM_I1(NRS),XLLIM_IM(NRS)
      REAL :: XLLIM_K1(NRS),XLLIM_KM(NRS)
      REAL :: XLLIM_DWN(NRS),XLLIM_UP(NRS)
      REAL :: CFWALL,FMIXUP,FACMIXUP
      INTEGER :: NMIXUP
      REAL :: YPLUSWALL
      INTEGER :: I_ROUGH
      REAL :: TURBVIS_LIM
      REAL :: ROUGH_H(NRS),ROUGH_T(NRS)
      REAL :: ROUGH_L(NRS),ROUGH_U(NRS)
      REAL :: REYNOLDS(NRS),CHORD(NRS)
      REAL :: ROVEXIT(NRS),VISCOSY(NRS)
      REAL :: RF_VIS,RF_VIS1
      REAL, ALLOCATABLE :: DPDS_CELL(:,:,:)
C
C=== BKINPT ===========================================================
C
      REAL, ALLOCATABLE :: PO1(:),TO1(:),RPO1(:)
      REAL, ALLOCATABLE :: BS(:),BR(:),VM1(:)
      REAL, ALLOCATABLE :: PD(:),VTIN(:),PLIM(:)
      REAL :: PDOWN_HUB,PDOWN_TIP
      INTEGER :: IF_REPEAT,NINMOD
      REAL :: RFINBC,THROTTLE_EXIT,PLATE_LOSS
      REAL :: THROTTLE_PRES,THROTTLE_MAS,RFTHROTL,RFTHROTL1
      REAL :: F_PDOWN
C
C=== BKMGRD ===========================================================
C
      INTEGER :: IR,JR,KR,IRBB,JRBB,KRBB
      INTEGER, ALLOCATABLE :: JSBLK(:)
      REAL :: FBLK1,FBLK2,FBLK3
      INTEGER, ALLOCATABLE :: IB1(:),IB2(:),KB1(:),KB2(:)
      INTEGER, ALLOCATABLE :: JB1(:),JB2(:)
      INTEGER :: NIB1,NIB2,NJB1,NJB2,NKB1,NKB2,NSBLK
      REAL :: STEP1(IG1,JG1,KG1)
      REAL :: STEP2(IG2,JG2,KG2)
      REAL :: STEPSBK(JG3)
      REAL :: AVG_CHG(NRS),AVG_BLK(NRS)
C
C=== BKGAS ============================================================
C
      REAL :: CP,GA,FGA,GA1,RGAS,RCP,CV,RCV,RFGA
      REAL :: PRANDTL,FTCOND,HOREF
      INTEGER :: IFGAS
      REAL :: CP1,CP2,CP3,CV1,TREF,HREF
      REAL :: HT1,HT2,HT3,HT4
      REAL :: ET1,ET2,ET3,ET4,EREF
      REAL :: ALPHA,R_ALPHA,BETA1,BETA2,BALPHA1,BALPHA2
      REAL :: EPS0,EPS1,EPS2
      REAL :: GAGAS,FGAGAS,GA1GAS
C
C=== BKCNTL ===========================================================
C
      REAL :: CFL,W,FUP,RFUP,DAMP,DAMPIN,FVMIN,CONLIM,RPM
      REAL :: ROVM_REF,VSOUND,RO_REF,PO_REF,DP_DRO
      REAL :: RF_PTRU,RF_PTRU1,DENSTY
      REAL :: MACHLIM
      REAL :: RFIN,RFIN1,RFIN2
      REAL :: VLIMIT(NRS)
      REAL :: RF_VSOUND,RF_VSOUND1,VS_VMAX
      REAL :: ROLIMIT(NRS),ROLIM,RO_MIN
      REAL :: ROELIMIT(NRS)
      REAL, ALLOCATABLE :: PXTRAP(:)
      REAL :: REL_M_MAX
      INTEGER :: IMACH,JMACH,KMACH
C
C=== BKSTAG ===========================================================
C
      INTEGER :: NROWS
      INTEGER, ALLOCATABLE :: IND(:),INDLE(:),INDMIX(:)
      INTEGER, ALLOCATABLE :: NBLADE(:)
      REAL, ALLOCATABLE :: WRAD(:),PGUESS(:),RATPIT(:)
      INTEGER, ALLOCATABLE :: NROW(:),INDMID(:)
      INTEGER :: NRWSM1
      REAL, ALLOCATABLE :: FPOLY(:,:)
      INTEGER, ALLOCATABLE :: INDTE(:)
      INTEGER :: JMIX(NRS),JSTART(NRS+1)
      INTEGER :: IFMIX
      REAL :: RFMIX,FSMTHB,FMACH
      INTEGER :: JLED(NRS)
      REAL, ALLOCATABLE :: FACXDIF(:)
      REAL, ALLOCATABLE :: ALPHA_S(:,:,:)
      INTEGER :: NSTAGE(NRS+1),JSTG_START(NRS),JSTG_END(NRS)
      INTEGER :: NSTAGES
      INTEGER :: IF_CUSP(NRS),NUP_I1(NRS),NUP_IM(NRS)
      INTEGER :: N_WAKE(NRS)
      REAL :: SEP_THIK(NRS),SEP_DRAG(NRS)
      REAL :: FEXTRAP,FANGLE
      REAL, ALLOCATABLE :: UBLADE(:,:)
C
C=== BKTIP ============================================================
C
      INTEGER, ALLOCATABLE :: KTIPS(:),KTIPE(:)
      REAL, ALLOCATABLE :: FTHICK(:,:)
      REAL, ALLOCATABLE :: WHUB(:),WTIP(:)
      INTEGER, ALLOCATABLE :: KS1(:),KS2(:)
      REAL :: FRACTIP(NRS),FRACTIP1(NRS),FRACTIP2(NRS)
C
C=== BKDIFF ===========================================================
C
      REAL, ALLOCATABLE :: DRO(:,:,:)
      REAL, ALLOCATABLE :: DROE(:,:,:)
      REAL, ALLOCATABLE :: DROVX(:,:,:)
      REAL, ALLOCATABLE :: DROVR(:,:,:)
      REAL, ALLOCATABLE :: DRORVT(:,:,:)
C
C=== BKDIST ===========================================================
C
      REAL, ALLOCATABLE :: FTL(:,:),FBL(:,:)
      REAL, ALLOCATABLE :: FTR(:,:),FBR(:,:)
C
C=== BKSHROUD =========================================================
C
      INTEGER :: KSHROUD(NRS)
      INTEGER :: JLEAKS(NRS),JLEAKE(NRS)
      INTEGER :: JLKINS(NRS),JLKINE(NRS)
      REAL :: SEALGAP(NRS)
      INTEGER :: NSEAL(NRS)
      REAL :: CFSHROUD(NRS),CFCASING(NRS),PITCHIN(NRS)
      REAL, ALLOCATABLE :: AS(:,:)
      REAL :: WCASE(NRS)
      REAL, ALLOCATABLE :: POAX(:,:),TOAX(:,:)
      REAL, ALLOCATABLE :: SHRDFLOW(:)
      REAL :: SLEAK(NRS),SWORK(NRS),SWORKTOT
      REAL, ALLOCATABLE :: HOAX(:,:)
C
C=== BKSHRDFLUX =======================================================
C
      REAL, ALLOCATABLE :: SHROUDGR(:,:)
      REAL, ALLOCATABLE :: SHROUDHO(:,:)
      REAL, ALLOCATABLE :: SHROUDVX(:,:)
      REAL, ALLOCATABLE :: SHROUDRVT(:,:)
      REAL, ALLOCATABLE :: SHROUDVR(:,:)
C
C=== BKCOOL ===========================================================
C
      REAL, ALLOCATABLE :: CFLOWI1(:,:),CFLOWIM(:,:)
      REAL, ALLOCATABLE :: CFLOWK1(:,:),CFLOWKM(:,:)
      REAL, ALLOCATABLE :: VXCWLI1(:,:),VXCWLIM(:,:)
      REAL, ALLOCATABLE :: VXCWLK1(:,:),VXCWLKM(:,:)
      REAL, ALLOCATABLE :: VRCWLI1(:,:),VRCWLIM(:,:)
      REAL, ALLOCATABLE :: VRCWLK1(:,:),VRCWLKM(:,:)
      REAL, ALLOCATABLE :: HOCWLI1(:,:),HOCWLIM(:,:)
      REAL, ALLOCATABLE :: HOCWLK1(:,:),HOCWLKM(:,:)
      REAL, ALLOCATABLE :: RVTCWLI1(:,:),RVTCWLIM(:,:)
      REAL, ALLOCATABLE :: RVTCWLK1(:,:),RVTCWLKM(:,:)
      REAL :: WRAD_COOLB(NCWL),WRAD_COOLW(NCWL)
      INTEGER :: IC(NCWL),JCBS(NCWL),JCBE(NCWL)
      INTEGER :: KC(NCWL),KCBS(NCWL),KCBE(NCWL)
      INTEGER :: JCWS(NCWL),JCWE(NCWL)
      INTEGER :: ICWS(NCWL),ICWE(NCWL)
      INTEGER :: NCOOLB,NCOOLW
      REAL, ALLOCATABLE :: SUMCWL(:)
      REAL :: TORELB(NCWL),TORELW(NCWL)
      REAL :: TCOOL_MIN
      REAL :: TSTAT_EJECTB(NCWL),TSTAT_EJECTW(NCWL)
      REAL :: PO_EJECTB(NCWL),PO_EJECTW(NCWL)
C
C=== BKCWL ============================================================
C
      REAL :: CFLOWB(NCWL),CFLOWW(NCWL)
      REAL :: ACOOLB(NCWL),ACOOLW(NCWL)
      REAL :: TOCOOLB(NCWL),TOCOOLW(NCWL)
      REAL :: POCOOLB(NCWL),POCOOLW(NCWL)
      REAL :: MACHCOOL(NCWL)
      REAL :: XANGLEB(NCWL),SANGLEB(NCWL)
      REAL :: SANGLEW(NCWL),TANGLEW(NCWL)
      REAL :: RVT_IN_B(NCWL),RVT_IN_W(NCWL)
      REAL :: WPUMP(NRS)
C
C=== BKATOT ===========================================================
C
      REAL, ALLOCATABLE :: ATOTK1(:,:),ATOTKM(:,:)
      REAL, ALLOCATABLE :: ATOTI1(:,:),ATOTIM(:,:)
C
C=== BKBLEED ==========================================================
C
      REAL, ALLOCATABLE :: BLFLOWI1(:,:),BLFLOWIM(:,:)
      REAL, ALLOCATABLE :: BLFLOWK1(:,:),BLFLOWKM(:,:)
      REAL, ALLOCATABLE :: SUMBLEED(:)
C
C=== BKOUT ============================================================
C
      REAL, ALLOCATABLE :: PO_OUT_AVG(:),TO_OUT_AVG(:)
      REAL, ALLOCATABLE :: YAW_OUT_AVG(:),PITCH_OUT_AVG(:)
      REAL, ALLOCATABLE :: VT_OUT_AVG(:)
      REAL :: TO_IN_MID,PO_IN_MID,VT_IN_MID
      REAL :: YAW_IN_MID,PITCH_IN_MID
C
C=== BKNEWLOS =========================================================
C
      REAL, ALLOCATABLE :: DIST_MIN(:,:,:)
      REAL, ALLOCATABLE :: XLENGTH(:,:,:)
      REAL, ALLOCATABLE :: XLIMIT(:)
      REAL :: XLLIM_IN(NRS),XLLIM_LE(NRS)
      REAL :: XLLIM_TE(NRS),XLLIM_DN(NRS)
      REAL, ALLOCATABLE :: VISC_LAM(:,:,:)
      REAL, ALLOCATABLE :: VISC_RAT(:,:,:)
      REAL, ALLOCATABLE :: FST_RAT(:,:,:)
      REAL :: FSTURB(NRS)
      REAL :: VORT_MAX
      REAL, ALLOCATABLE :: Y_PLUS(:,:,:)
      REAL :: YPLAM,YPTURB
      REAL, ALLOCATABLE :: YPLUS_K1(:,:),YPLUS_KM(:,:)
      REAL, ALLOCATABLE :: YPLUS_I1(:,:),YPLUS_IM(:,:)
C
C=== BKSPALOS =========================================================
C
      REAL, ALLOCATABLE :: TRANS_KVIS(:,:,:)
      REAL, ALLOCATABLE :: TRANS_DYN_VIS(:,:,:)
      REAL, ALLOCATABLE :: DYN_VIS_ML(:,:,:)
      REAL, ALLOCATABLE :: TRANS_VORT(:,:,:)
      REAL, ALLOCATABLE :: DEL_DYNVIS(:,:,:)
      REAL :: TURB_FORCE
      REAL, ALLOCATABLE :: ROAVG_CELL(:,:,:)
      REAL, ALLOCATABLE :: ABS_VORT(:,:,:)
      REAL, ALLOCATABLE :: GRAD_TVIS(:,:,:)
      REAL, ALLOCATABLE :: T_SOURCE(:,:,:)
      REAL, ALLOCATABLE :: DWALLSQ(:,:,:)
      REAL, ALLOCATABLE :: TVISGRADX(:,:,:)
      REAL, ALLOCATABLE :: TVISGRADR(:,:,:)
      REAL, ALLOCATABLE :: TVISGRADT(:,:,:)
      REAL :: TURBVIS_DAMP(NRS)
      REAL, ALLOCATABLE :: VISC_TURB(:,:,:)
      REAL :: FAC_ST0,FAC_ST1,FAC_ST2,FAC_ST3
      REAL :: FAC_STMIX,FAC_SFVIS,FAC_VORT,FAC_PGRAD
      REAL, ALLOCATABLE :: SPAREVAR(:,:,:)
C
C=== BKTFLOW ==========================================================
C
      REAL :: SFPBLD,SFPBLD1
      INTEGER :: NSFPBLD
      REAL :: Q3DFORCE
      REAL, ALLOCATABLE :: AVGPBLADE(:)
      REAL, ALLOCATABLE :: PBLADE(:,:),ROVAR_M1(:,:)
      REAL, ALLOCATABLE :: BFORCE_X(:,:),BFORCE_R(:,:)
      REAL, ALLOCATABLE :: BFORCE_T(:,:),BFORCE_Q(:,:)
      REAL, ALLOCATABLE :: SFACPB(:)
      REAL, ALLOCATABLE :: DEVN_ANGL(:,:),EXIT_ANGL(:,:)
      REAL, ALLOCATABLE :: FRAC_SPAN(:,:)
      REAL, ALLOCATABLE :: EXANG(:)
      REAL, ALLOCATABLE :: ALPHA_CENT(:,:)
      INTEGER :: NANGLES(NRS),IF_DEVN(NRS)
      REAL, ALLOCATABLE :: CENT_ANGL(:),S_DIST(:)
C
C=== BKINVERSE ========================================================
C
      REAL, ALLOCATABLE :: PSPEC_I1(:),PSPEC_IM(:)
      REAL :: X_IN(25),P_IN(25)
      REAL, ALLOCATABLE :: SDIST(:)
      REAL, ALLOCATABLE :: YMOVE_I1(:),YMOVE_IM(:)
      INTEGER :: N_UPP,J_LEDGE,J_TEDGE
      REAL :: A2_SPEC,A2_NOW,A2_COMP,A2_SET
      REAL :: ROT_FAK,ANG_FAK,R_FAK_I1,R_FAK_IM,S_FAK
      REAL, ALLOCATABLE :: SUM_SOURCE_I1(:),SUM_SOURCE_IM(:)
      INTEGER :: IFINV_I1,IFINV_IM,N_SMTH
      REAL :: F_SMTH
      REAL, ALLOCATABLE :: TKLIM(:),ABT_MID(:),FRAC_ABT(:)
      REAL, ALLOCATABLE :: S_MERID(:),PDIV(:)
      REAL :: FAK_SCL
      REAL, ALLOCATABLE :: P_AVGG(:)
      REAL, ALLOCATABLE :: SUM_MOVE_I1(:),SUM_MOVE_IM(:)
      REAL, ALLOCATABLE :: FRAC_CRD(:),RT_MID(:)
      REAL, ALLOCATABLE :: FSOURCE(:)
      REAL :: TKEXP
      REAL, ALLOCATABLE :: DY_ROTN(:)
      REAL :: TKMOVE,TKMVM1
      INTEGER :: IF_INV,NINV_START,NINV_END,NINV_UPP
      REAL :: FTK
      REAL, ALLOCATABLE :: TK_SURF(:)
      REAL :: TK_SCALE
      REAL, ALLOCATABLE :: TKORIG(:)
      REAL :: FRACMV,FRACMV1
      REAL, ALLOCATABLE :: SURF_FLUX(:)
      REAL :: RF_SCALE,RF_THICK
      REAL :: TK_ADD_LE,TK_ADD_TE,A2_COMP_NEW
      REAL, ALLOCATABLE :: TKLIN(:)
      INTEGER :: JSET_TK
      REAL, ALLOCATABLE :: TKSET(:),TKMIN(:),TK_DIFF(:)
      INTEGER :: ISUCT,IPRESS
      REAL, ALLOCATABLE :: ROVMER(:)
C
C=== BKTABLES =========================================================
C
      REAL, ALLOCATABLE :: RGAS_NOW(:,:,:)
      REAL, ALLOCATABLE :: PHEXP(:,:,:)
      REAL, ALLOCATABLE :: GA_PV(:,:,:)
      REAL, ALLOCATABLE :: WET(:,:,:)
      REAL, ALLOCATABLE :: H_TO_T(:,:,:)
      REAL, ALLOCATABLE :: ENTPY(:,:,:)
      REAL :: RSTEAM,GAMSTEAM
      REAL :: UMAX,UMIN,ROMAX,ROMIN
      REAL, ALLOCATABLE :: UINT(:,:)
C
C=== BLKTAB ===========================================================
C
      REAL :: P_TAB(ITB,JTB),RO_TAB(ITB,JTB)
      REAL :: U_TAB(ITB,JTB),T_TAB(ITB,JTB)
      REAL :: Z1(ITB,JTB)
      REAL :: W1(ITB,101),W2(ITB,101)
      REAL :: ENT_TAB(ITB,JTB),DRY_TAB(ITB,JTB)
      REAL :: P_HDI_TAB(ITB,JTB),P_HDJ_TAB(ITB,JTB)
      REAL :: T_HDI_TAB(ITB,JTB),T_HDJ_TAB(ITB,JTB)
      REAL :: ENT_HDI_TAB(ITB,JTB),ENT_HDJ_TAB(ITB,JTB)
      REAL :: GA_HDI_TAB(ITB,JTB),GA_HDJ_TAB(ITB,JTB)
      REAL :: DRY_HDI_TAB(ITB,JTB),DRY_HDJ_TAB(ITB,JTB)
      REAL :: HPPOLY(ITB,JTB),GA_PV_TAB(ITB,JTB)
      INTEGER :: ITAB,JTAB,I_MID,J_MID
      REAL, ALLOCATABLE :: HO_INN(:),ROSTAG_IN(:)
      REAL :: XVAL(ITB,JTB),YVAL(ITB,JTB)
      REAL :: ROAXIS(ITB),UAXIS(JTB)
      REAL :: HEIGHTS(JTB)
      REAL :: DROAXIS(ITB),DUAXIS(JTB)
      REAL :: ROMINN,ROMAXX,UMINN,UMAXX
C
C=== BKCHAR ===========================================================
C
      CHARACTER*72 :: TITLE, ROWTYP, DUMMY_INPUT, DUMMY
      CHARACTER*1  :: ANGL_TYP(NRS)
C
C=== BKSTRESS (shared between viscous subroutines) ====================
C
      REAL, ALLOCATABLE :: TXX(:,:,:),TXR(:,:,:),TXT(:,:,:)
      REAL, ALLOCATABLE :: TRX(:,:,:),TRR(:,:,:),TRT(:,:,:)
      REAL, ALLOCATABLE :: TTX(:,:,:),TTR(:,:,:),TTT(:,:,:)
      REAL, ALLOCATABLE :: QXX(:,:,:),QRR(:,:,:),QTT(:,:,:)
C
C=== Explicit type overrides ==========================================
C     MACHLIM in BKCNTL, MACHCOOL in BKCWL, M_REL in BKPRIM
      REAL :: MACHREL
C
C======================================================================
      CONTAINS
C======================================================================
C
      SUBROUTINE PRE_READIN_DIMS(ANS_IN,
     &                           IM_REQ,JM_REQ,KM_REQ,NROWS_REQ)
C
C     Lightweight pre-read for NEW format only.
C     Reads stable marker lines to determine IM,KM,NROWS.
C     JM is estimated from numeric row-control lines (3 integers).
C     If estimation fails, JM falls back to JD.
C
      CHARACTER*1 ANS_IN
      INTEGER IM_REQ,JM_REQ,KM_REQ,NROWS_REQ
      CHARACTER*256 LINE
      INTEGER IOS, IOS2, IOS3, IOS4
      INTEGER I1, I2, I3, I4
      INTEGER JM_SUM, N_JMROW
      LOGICAL FOUND_NROWS, FOUND_IMKM
      LOGICAL FOUND_JM

      IF(ANS_IN.NE.'N'.AND.ANS_IN.NE.'n') THEN
           WRITE(6,*) ' PRE_READIN_DIMS: only NEW format supported.'
           STOP
      END IF
      REWIND(5)
      FOUND_NROWS = .FALSE.
      FOUND_IMKM  = .FALSE.
      FOUND_JM    = .FALSE.
      JM_SUM      = 0
      N_JMROW     = 0

 1000 CONTINUE
      READ(5,'(A)',IOSTAT=IOS) LINE
      IF(IOS.NE.0) GO TO 2000

      IF((.NOT.FOUND_NROWS).AND.
     &   INDEX(LINE,'NUMBER OF BLADE ROWS').GT.0) THEN
           READ(5,'(A)',IOSTAT=IOS) LINE
           IF(IOS.NE.0) GO TO 9000
           READ(LINE,*,IOSTAT=IOS2) NROWS_REQ
           IF(IOS2.NE.0) GO TO 9000
           FOUND_NROWS = .TRUE.
           GO TO 1000
      END IF

      IF((.NOT.FOUND_IMKM).AND.
     &   INDEX(LINE,'GRID POINT NUMBERS').GT.0) THEN
           READ(5,'(A)',IOSTAT=IOS) LINE
           IF(IOS.NE.0) GO TO 9000
           READ(LINE,*,IOSTAT=IOS2) IM_REQ,KM_REQ
           IF(IOS2.NE.0) GO TO 9000
           FOUND_IMKM = .TRUE.
           GO TO 1000
      END IF

      IF(FOUND_NROWS.AND.FOUND_IMKM.AND.(.NOT.FOUND_JM)) THEN
           IF(INDEX(LINE,'.').EQ.0) THEN
                READ(LINE,*,IOSTAT=IOS4) I1,I2,I3,I4
                IF(IOS4.NE.0) THEN
                     READ(LINE,*,IOSTAT=IOS3) I1,I2,I3
                     IF(IOS3.EQ.0) THEN
                          IF(I1.GE.2.AND.I1.LE.JD.AND.
     &                       I2.GE.1.AND.I2.LE.I1.AND.
     &                       I3.GE.1.AND.I3.LE.I1) THEN
                               JM_SUM  = JM_SUM + I1
                               N_JMROW = N_JMROW + 1
                               IF(N_JMROW.EQ.NROWS_REQ)
     &                              FOUND_JM = .TRUE.
                          END IF
                     END IF
                END IF
           END IF
      END IF

      GO TO 1000

 2000 CONTINUE
      IF((.NOT.FOUND_NROWS).OR.(.NOT.FOUND_IMKM)) GO TO 9000

      IF(FOUND_JM) THEN
           JM_REQ = JM_SUM
      ELSE
           JM_REQ = JD
      END IF

      REWIND(5)
      RETURN

 9000 CONTINUE
      WRITE(6,*) ' PRE_READIN_DIMS: input pre-read failed.'
      STOP
      END SUBROUTINE PRE_READIN_DIMS
C
C----------------------------------------------------------------------
C
      SUBROUTINE ALLOC_MULTALL_DATA(ID_REQ,JD_REQ,KD_REQ,
     &                              NROWS_REQ)
      INTEGER ID_REQ,JD_REQ,KD_REQ,NROWS_REQ
C
C     Set runtime dimensions
C
      ID = ID_REQ
      JD = JD_REQ
      KD = KD_REQ
      MAXKI = MAX(ID, KD)
      IM_ALLOC    = ID_REQ
      JM_ALLOC    = JD_REQ
      KM_ALLOC    = KD_REQ
      NROWS_ALLOC = NROWS_REQ
C
      WRITE(6,*) ' ALLOC_MULTALL_DATA: ID,JD,KD,MAXKI,NROWS = ',
     &            ID,JD,KD,MAXKI,NROWS_ALLOC
C
C     Deallocate if already allocated
C
      IF(IALLOC_STATE.EQ.1) CALL DEALLOC_MULTALL_DATA
C
C --- BKINTG: MAXKI-dimensioned ---
      ALLOCATE(KOUT(MAXKI))
      ALLOCATE(JLE(MAXKI), JTE(MAXKI))
C --- BKUTIL: 3D arrays ---
      ALLOCATE(STORE(ID,JD,KD))
      ALLOCATE(TEMP1(ID,JD,KD))
      ALLOCATE(TEMP2(ID,JD,KD))
      ALLOCATE(TEMP3(ID,JD,KD))
      ALLOCATE(TEMP4(ID,JD,KD))
      ALLOCATE(STORE2(ID,JD,KD))
      ALLOCATE(SGEN(ID,JD,KD))
C --- BKINTG: 1D ---
      ALLOCATE(INDLETE(JD))
C --- BKGEOM: 2D, 3D, 1D ---
      ALLOCATE(X(JD,KD), R(JD,KD))
      ALLOCATE(RSURF(JD,KD), SMERID(JD,KD))
      ALLOCATE(XSURF(JD,KD), DS(JD,KD))
      ALLOCATE(RAVG_CELL(JD,KD))
      ALLOCATE(RCYL(MAXKI))
      ALLOCATE(DR(JD,KD))
      ALLOCATE(THETA(ID,JD,KD))
      ALLOCATE(DX(JD,KD))
      ALLOCATE(RT_UPP(JD,KD), RT_THICK(JD,KD))
      ALLOCATE(RT_PITCH(JD,KD))
      ALLOCATE(RTHETA(ID,JD,KD))
      ALLOCATE(BETAUP(NRS,KD))
      ALLOCATE(BETADWN1(NRS,KD), BETADWN2(NRS,KD))
      ALLOCATE(FRACN_SPAN(KD))
      ALLOCATE(ANGL_UP(KD),ANGL_DWN1(KD),ANGL_DWN2(KD))
C --- BKAREA ---
      ALLOCATE(ABX(ID,JD,KD), ABR(ID,JD,KD))
      ALLOCATE(AQX(ID,JD,KD), AQR(ID,JD,KD))
      ALLOCATE(ASX(ID,JD,KD), ASR(ID,JD,KD))
      ALLOCATE(ABT(JD,KD), WRABT(JD,KD))
      ALLOCATE(VOL(ID,JD,KD), VOLOR(ID,JD,KD))
      ALLOCATE(AQTOT(ID,JD,KD), ABTOT(ID,JD,KD))
C --- BKFLUX ---
      ALLOCATE(XFLUX(ID,JD,KD), TFLUX(ID,JD,KD))
      ALLOCATE(RFLUX(ID,JD,KD))
      ALLOCATE(STEP(ID,JD,KD), BSTEP(ID,JD,KD))
      ALLOCATE(RSTEP(ID,JD,KD), SOURCE(ID,JD,KD))
C --- BKFLOW ---
      ALLOCATE(FLOWX(ID,JD,KD), FLOWR(ID,JD,KD))
      ALLOCATE(FLOWT(ID,JD,KD))
C --- BKSEC ---
      ALLOCATE(VX(ID,JD,KD), VR(ID,JD,KD), VT(ID,JD,KD))
      ALLOCATE(PEFF(ID,JD,KD), T_STATIC(ID,JD,KD))
      ALLOCATE(WT(ID,JD,KD))
C --- BKPRIM ---
      ALLOCATE(RO(ID,JD,KD), P(ID,JD,KD))
      ALLOCATE(ROE(ID,JD,KD), ROVX(ID,JD,KD))
      ALLOCATE(ROVR(ID,JD,KD), ROVT(ID,JD,KD))
      ALLOCATE(RORVT(ID,JD,KD), HO(ID,JD,KD))
      ALLOCATE(ROSUB(ID,JD,KD), ROWT(ID,JD,KD))
      ALLOCATE(M_REL(ID,JD,KD))
C --- BKFFLO ---
      ALLOCATE(FLOW(JD))
C --- BKFRAC ---
      ALLOCATE(FR(MAXKI), FR_IN(MAXKI))
      ALLOCATE(FP(ID))
      ALLOCATE(FKU(KD), FKD(KD))
      ALLOCATE(FU(ID), FD(ID))
      ALLOCATE(BSSIN(MAXKI), BSCOS(MAXKI))
      ALLOCATE(BRSIN(MAXKI), BRCOS(MAXKI))
      ALLOCATE(FMUP(JD,KD), FMDN(JD,KD))
      ALLOCATE(FACUP(JD), FACDWN(JD))
      ALLOCATE(FSPAN(KD), QSPAN(KD))
C --- BKLOSS ---
      ALLOCATE(XFORCE(ID,JD,KD), RFORCE(ID,JD,KD))
      ALLOCATE(TFORCE(ID,JD,KD), QSOURCE(ID,JD,KD))
      ALLOCATE(VLAM(MAXKI), VTURB(MAXKI))
      ALLOCATE(FKLAM(NRS,MAXKI), FKTURB(NRS,MAXKI))
      ALLOCATE(FILAM(NRS,MAXKI), FITURB(NRS,MAXKI))
      ALLOCATE(FIWAKE(NRS,MAXKI), FIUP(NRS,MAXKI))
      ALLOCATE(JTRAN_I1(MAXKI), JTRAN_IM(MAXKI))
      ALLOCATE(JTRAN_K1(MAXKI), JTRAN_KM(MAXKI))
      ALLOCATE(DPDS_CELL(ID,JD,KD))
C --- BKINPT ---
      ALLOCATE(PO1(MAXKI), TO1(MAXKI), RPO1(MAXKI))
      ALLOCATE(BS(MAXKI), BR(MAXKI), VM1(MAXKI))
      ALLOCATE(PD(MAXKI), VTIN(MAXKI), PLIM(MAXKI))
C --- BKMGRD ---
      ALLOCATE(JSBLK(JD))
      ALLOCATE(IB1(MAXKI), IB2(MAXKI))
      ALLOCATE(KB1(MAXKI), KB2(MAXKI))
      ALLOCATE(JB1(JD), JB2(JD))
C --- BKCNTL ---
      ALLOCATE(PXTRAP(ID))
C --- BKSTAG ---
      ALLOCATE(IND(JD), INDLE(JD), INDMIX(JD))
      ALLOCATE(NBLADE(JD))
      ALLOCATE(WRAD(JD), PGUESS(JD), RATPIT(JD))
      ALLOCATE(NROW(JD), INDMID(JD))
      ALLOCATE(INDTE(JD))
      ALLOCATE(FACXDIF(JD))
      ALLOCATE(ALPHA_S(ID,KD,NRS))
      ALLOCATE(FPOLY(NRS,MAXKI))
      ALLOCATE(UBLADE(JD,KD))
C --- BKTIP ---
      ALLOCATE(KTIPS(MAXKI), KTIPE(MAXKI))
      ALLOCATE(FTHICK(NRS,MAXKI))
      ALLOCATE(WHUB(JD), WTIP(JD))
      ALLOCATE(KS1(MAXKI), KS2(MAXKI))
C --- BKDIFF ---
      ALLOCATE(DRO(ID,JD,KD), DROE(ID,JD,KD))
      ALLOCATE(DROVX(ID,JD,KD), DROVR(ID,JD,KD))
      ALLOCATE(DRORVT(ID,JD,KD))
C --- BKDIST ---
      ALLOCATE(FTL(ID,KD), FBL(ID,KD))
      ALLOCATE(FTR(ID,KD), FBR(ID,KD))
C --- BKSHROUD ---
      ALLOCATE(AS(ID,JD))
      ALLOCATE(POAX(ID,JD), TOAX(ID,JD))
      ALLOCATE(SHRDFLOW(JD))
      ALLOCATE(HOAX(ID,JD))
C --- BKSHRDFLUX ---
      ALLOCATE(SHROUDGR(ID,JD), SHROUDHO(ID,JD))
      ALLOCATE(SHROUDVX(ID,JD), SHROUDRVT(ID,JD))
      ALLOCATE(SHROUDVR(ID,JD))
C --- BKCOOL ---
      ALLOCATE(CFLOWI1(JD,KD), CFLOWIM(JD,KD))
      ALLOCATE(CFLOWK1(ID,JD), CFLOWKM(ID,JD))
      ALLOCATE(VXCWLI1(JD,KD), VXCWLIM(JD,KD))
      ALLOCATE(VXCWLK1(ID,JD), VXCWLKM(ID,JD))
      ALLOCATE(VRCWLI1(JD,KD), VRCWLIM(JD,KD))
      ALLOCATE(VRCWLK1(ID,JD), VRCWLKM(ID,JD))
      ALLOCATE(HOCWLI1(JD,KD), HOCWLIM(JD,KD))
      ALLOCATE(HOCWLK1(ID,JD), HOCWLKM(ID,JD))
      ALLOCATE(RVTCWLI1(JD,KD), RVTCWLIM(JD,KD))
      ALLOCATE(RVTCWLK1(ID,JD), RVTCWLKM(ID,JD))
      ALLOCATE(SUMCWL(JD))
C --- BKATOT ---
      ALLOCATE(ATOTK1(ID,JD), ATOTKM(ID,JD))
      ALLOCATE(ATOTI1(JD,KD), ATOTIM(JD,KD))
C --- BKBLEED ---
      ALLOCATE(BLFLOWI1(JD,KD), BLFLOWIM(JD,KD))
      ALLOCATE(BLFLOWK1(ID,JD), BLFLOWKM(ID,JD))
      ALLOCATE(SUMBLEED(JD))
C --- BKOUT ---
      ALLOCATE(PO_OUT_AVG(KD), TO_OUT_AVG(KD))
      ALLOCATE(YAW_OUT_AVG(KD), PITCH_OUT_AVG(KD))
      ALLOCATE(VT_OUT_AVG(KD))
C --- BKNEWLOS ---
      ALLOCATE(DIST_MIN(ID,JD,KD), XLENGTH(ID,JD,KD))
      ALLOCATE(XLIMIT(JD))
      ALLOCATE(VISC_LAM(ID,JD,KD), VISC_RAT(ID,JD,KD))
      ALLOCATE(FST_RAT(ID,JD,KD))
      ALLOCATE(Y_PLUS(ID,JD,KD))
      ALLOCATE(YPLUS_K1(ID,JD), YPLUS_KM(ID,JD))
      ALLOCATE(YPLUS_I1(JD,KD), YPLUS_IM(JD,KD))
C --- BKSPALOS ---
      ALLOCATE(TRANS_KVIS(ID,JD,KD))
      ALLOCATE(TRANS_DYN_VIS(ID,JD,KD))
      ALLOCATE(DYN_VIS_ML(ID,JD,KD))
      ALLOCATE(TRANS_VORT(ID,JD,KD))
      ALLOCATE(DEL_DYNVIS(ID,JD,KD))
      ALLOCATE(ROAVG_CELL(ID,JD,KD))
      ALLOCATE(ABS_VORT(ID,JD,KD))
      ALLOCATE(GRAD_TVIS(ID,JD,KD))
      ALLOCATE(T_SOURCE(ID,JD,KD))
      ALLOCATE(DWALLSQ(ID,JD,KD))
      ALLOCATE(TVISGRADX(ID,JD,KD))
      ALLOCATE(TVISGRADR(ID,JD,KD))
      ALLOCATE(TVISGRADT(ID,JD,KD))
      ALLOCATE(VISC_TURB(ID,JD,KD))
      ALLOCATE(SPAREVAR(ID,JD,KD))
C --- BKTFLOW ---
      ALLOCATE(AVGPBLADE(JD))
      ALLOCATE(PBLADE(JD,KD), ROVAR_M1(JD,KD))
      ALLOCATE(BFORCE_X(JD,KD), BFORCE_R(JD,KD))
      ALLOCATE(BFORCE_T(JD,KD), BFORCE_Q(JD,KD))
      ALLOCATE(SFACPB(JD))
      ALLOCATE(DEVN_ANGL(NRS,KD), EXIT_ANGL(NRS,KD))
      ALLOCATE(FRAC_SPAN(NRS,KD))
      ALLOCATE(EXANG(KD))
      ALLOCATE(ALPHA_CENT(JD,KD))
      ALLOCATE(CENT_ANGL(JD), S_DIST(JD))
C --- BKINVERSE ---
      ALLOCATE(PSPEC_I1(JD), PSPEC_IM(JD))
      ALLOCATE(SDIST(JD))
      ALLOCATE(YMOVE_I1(JD), YMOVE_IM(JD))
      ALLOCATE(SUM_SOURCE_I1(JD), SUM_SOURCE_IM(JD))
      ALLOCATE(TKLIM(JD), ABT_MID(JD), FRAC_ABT(JD))
      ALLOCATE(S_MERID(JD), PDIV(JD))
      ALLOCATE(P_AVGG(JD))
      ALLOCATE(SUM_MOVE_I1(JD), SUM_MOVE_IM(JD))
      ALLOCATE(FRAC_CRD(JD), RT_MID(JD))
      ALLOCATE(FSOURCE(JD))
      ALLOCATE(DY_ROTN(JD))
      ALLOCATE(TK_SURF(JD))
      ALLOCATE(TKORIG(JD))
      ALLOCATE(SURF_FLUX(JD))
      ALLOCATE(TKLIN(JD))
      ALLOCATE(TKSET(JD), TKMIN(JD), TK_DIFF(JD))
      ALLOCATE(ROVMER(JD))
C --- BKTABLES ---
      ALLOCATE(RGAS_NOW(ID,JD,KD), PHEXP(ID,JD,KD))
      ALLOCATE(GA_PV(ID,JD,KD), WET(ID,JD,KD))
      ALLOCATE(H_TO_T(ID,JD,KD), ENTPY(ID,JD,KD))
      ALLOCATE(UINT(JD,KD))
C --- BLKTAB (KD-dependent only) ---
      ALLOCATE(HO_INN(KD), ROSTAG_IN(KD))
C --- BKSTRESS ---
      ALLOCATE(TXX(ID,JD,KD), TXR(ID,JD,KD), TXT(ID,JD,KD))
      ALLOCATE(TRX(ID,JD,KD), TRR(ID,JD,KD), TRT(ID,JD,KD))
      ALLOCATE(TTX(ID,JD,KD), TTR(ID,JD,KD), TTT(ID,JD,KD))
      ALLOCATE(QXX(ID,JD,KD), QRR(ID,JD,KD), QTT(ID,JD,KD))
C
      IALLOC_STATE = 1
      WRITE(6,*) ' ALLOC_MULTALL_DATA: allocation complete.'
      RETURN
      END SUBROUTINE ALLOC_MULTALL_DATA
C
C----------------------------------------------------------------------
C
      SUBROUTINE DEALLOC_MULTALL_DATA
C
      IF(IALLOC_STATE.NE.1) RETURN
C --- BKUTIL ---
      IF(ALLOCATED(STORE))  DEALLOCATE(STORE)
      IF(ALLOCATED(TEMP1))  DEALLOCATE(TEMP1)
      IF(ALLOCATED(TEMP2))  DEALLOCATE(TEMP2)
      IF(ALLOCATED(TEMP3))  DEALLOCATE(TEMP3)
      IF(ALLOCATED(TEMP4))  DEALLOCATE(TEMP4)
      IF(ALLOCATED(STORE2)) DEALLOCATE(STORE2)
      IF(ALLOCATED(SGEN))   DEALLOCATE(SGEN)
C --- BKINTG ---
      IF(ALLOCATED(KOUT))   DEALLOCATE(KOUT)
      IF(ALLOCATED(JLE))    DEALLOCATE(JLE)
      IF(ALLOCATED(JTE))    DEALLOCATE(JTE)
      IF(ALLOCATED(INDLETE)) DEALLOCATE(INDLETE)
C --- BKGEOM ---
      IF(ALLOCATED(X))      DEALLOCATE(X)
      IF(ALLOCATED(R))      DEALLOCATE(R)
      IF(ALLOCATED(RSURF))  DEALLOCATE(RSURF)
      IF(ALLOCATED(SMERID)) DEALLOCATE(SMERID)
      IF(ALLOCATED(XSURF))  DEALLOCATE(XSURF)
      IF(ALLOCATED(DS))     DEALLOCATE(DS)
      IF(ALLOCATED(RAVG_CELL)) DEALLOCATE(RAVG_CELL)
      IF(ALLOCATED(RCYL))   DEALLOCATE(RCYL)
      IF(ALLOCATED(DR))     DEALLOCATE(DR)
      IF(ALLOCATED(THETA))  DEALLOCATE(THETA)
      IF(ALLOCATED(DX))     DEALLOCATE(DX)
      IF(ALLOCATED(RT_UPP)) DEALLOCATE(RT_UPP)
      IF(ALLOCATED(RT_THICK)) DEALLOCATE(RT_THICK)
      IF(ALLOCATED(RT_PITCH)) DEALLOCATE(RT_PITCH)
      IF(ALLOCATED(RTHETA)) DEALLOCATE(RTHETA)
      IF(ALLOCATED(BETAUP)) DEALLOCATE(BETAUP)
      IF(ALLOCATED(BETADWN1)) DEALLOCATE(BETADWN1)
      IF(ALLOCATED(BETADWN2)) DEALLOCATE(BETADWN2)
      IF(ALLOCATED(FRACN_SPAN)) DEALLOCATE(FRACN_SPAN)
      IF(ALLOCATED(ANGL_UP)) DEALLOCATE(ANGL_UP)
      IF(ALLOCATED(ANGL_DWN1)) DEALLOCATE(ANGL_DWN1)
      IF(ALLOCATED(ANGL_DWN2)) DEALLOCATE(ANGL_DWN2)
C --- BKAREA ---
      IF(ALLOCATED(ABX))    DEALLOCATE(ABX)
      IF(ALLOCATED(ABR))    DEALLOCATE(ABR)
      IF(ALLOCATED(AQX))    DEALLOCATE(AQX)
      IF(ALLOCATED(AQR))    DEALLOCATE(AQR)
      IF(ALLOCATED(ASX))    DEALLOCATE(ASX)
      IF(ALLOCATED(ASR))    DEALLOCATE(ASR)
      IF(ALLOCATED(ABT))    DEALLOCATE(ABT)
      IF(ALLOCATED(WRABT))  DEALLOCATE(WRABT)
      IF(ALLOCATED(VOL))    DEALLOCATE(VOL)
      IF(ALLOCATED(VOLOR))  DEALLOCATE(VOLOR)
      IF(ALLOCATED(AQTOT))  DEALLOCATE(AQTOT)
      IF(ALLOCATED(ABTOT))  DEALLOCATE(ABTOT)
C --- BKFLUX ---
      IF(ALLOCATED(XFLUX))  DEALLOCATE(XFLUX)
      IF(ALLOCATED(TFLUX))  DEALLOCATE(TFLUX)
      IF(ALLOCATED(RFLUX))  DEALLOCATE(RFLUX)
      IF(ALLOCATED(STEP))   DEALLOCATE(STEP)
      IF(ALLOCATED(BSTEP))  DEALLOCATE(BSTEP)
      IF(ALLOCATED(RSTEP))  DEALLOCATE(RSTEP)
      IF(ALLOCATED(SOURCE)) DEALLOCATE(SOURCE)
C --- BKFLOW ---
      IF(ALLOCATED(FLOWX))  DEALLOCATE(FLOWX)
      IF(ALLOCATED(FLOWR))  DEALLOCATE(FLOWR)
      IF(ALLOCATED(FLOWT))  DEALLOCATE(FLOWT)
C --- BKSEC ---
      IF(ALLOCATED(VX))     DEALLOCATE(VX)
      IF(ALLOCATED(VR))     DEALLOCATE(VR)
      IF(ALLOCATED(VT))     DEALLOCATE(VT)
      IF(ALLOCATED(PEFF))   DEALLOCATE(PEFF)
      IF(ALLOCATED(T_STATIC)) DEALLOCATE(T_STATIC)
      IF(ALLOCATED(WT))     DEALLOCATE(WT)
C --- BKPRIM ---
      IF(ALLOCATED(RO))     DEALLOCATE(RO)
      IF(ALLOCATED(P))      DEALLOCATE(P)
      IF(ALLOCATED(ROE))    DEALLOCATE(ROE)
      IF(ALLOCATED(ROVX))   DEALLOCATE(ROVX)
      IF(ALLOCATED(ROVR))   DEALLOCATE(ROVR)
      IF(ALLOCATED(ROVT))   DEALLOCATE(ROVT)
      IF(ALLOCATED(RORVT))  DEALLOCATE(RORVT)
      IF(ALLOCATED(HO))     DEALLOCATE(HO)
      IF(ALLOCATED(ROSUB))  DEALLOCATE(ROSUB)
      IF(ALLOCATED(ROWT))   DEALLOCATE(ROWT)
      IF(ALLOCATED(M_REL))  DEALLOCATE(M_REL)
C --- BKFFLO ---
      IF(ALLOCATED(FLOW))   DEALLOCATE(FLOW)
C --- BKFRAC ---
      IF(ALLOCATED(FR))     DEALLOCATE(FR)
      IF(ALLOCATED(FR_IN))  DEALLOCATE(FR_IN)
      IF(ALLOCATED(FP))     DEALLOCATE(FP)
      IF(ALLOCATED(FKU))    DEALLOCATE(FKU)
      IF(ALLOCATED(FKD))    DEALLOCATE(FKD)
      IF(ALLOCATED(FU))     DEALLOCATE(FU)
      IF(ALLOCATED(FD))     DEALLOCATE(FD)
      IF(ALLOCATED(BSSIN))  DEALLOCATE(BSSIN)
      IF(ALLOCATED(BSCOS))  DEALLOCATE(BSCOS)
      IF(ALLOCATED(BRSIN))  DEALLOCATE(BRSIN)
      IF(ALLOCATED(BRCOS))  DEALLOCATE(BRCOS)
      IF(ALLOCATED(FMUP))   DEALLOCATE(FMUP)
      IF(ALLOCATED(FMDN))   DEALLOCATE(FMDN)
      IF(ALLOCATED(FACUP))  DEALLOCATE(FACUP)
      IF(ALLOCATED(FACDWN)) DEALLOCATE(FACDWN)
      IF(ALLOCATED(FSPAN))  DEALLOCATE(FSPAN)
      IF(ALLOCATED(QSPAN))  DEALLOCATE(QSPAN)
C --- BKLOSS ---
      IF(ALLOCATED(XFORCE)) DEALLOCATE(XFORCE)
      IF(ALLOCATED(RFORCE)) DEALLOCATE(RFORCE)
      IF(ALLOCATED(TFORCE)) DEALLOCATE(TFORCE)
      IF(ALLOCATED(QSOURCE))DEALLOCATE(QSOURCE)
      IF(ALLOCATED(VLAM))   DEALLOCATE(VLAM)
      IF(ALLOCATED(VTURB))  DEALLOCATE(VTURB)
      IF(ALLOCATED(FKLAM))  DEALLOCATE(FKLAM)
      IF(ALLOCATED(FKTURB)) DEALLOCATE(FKTURB)
      IF(ALLOCATED(FILAM))  DEALLOCATE(FILAM)
      IF(ALLOCATED(FITURB)) DEALLOCATE(FITURB)
      IF(ALLOCATED(FIWAKE)) DEALLOCATE(FIWAKE)
      IF(ALLOCATED(FIUP))   DEALLOCATE(FIUP)
      IF(ALLOCATED(JTRAN_I1)) DEALLOCATE(JTRAN_I1)
      IF(ALLOCATED(JTRAN_IM)) DEALLOCATE(JTRAN_IM)
      IF(ALLOCATED(JTRAN_K1)) DEALLOCATE(JTRAN_K1)
      IF(ALLOCATED(JTRAN_KM)) DEALLOCATE(JTRAN_KM)
      IF(ALLOCATED(DPDS_CELL)) DEALLOCATE(DPDS_CELL)
C --- BKINPT ---
      IF(ALLOCATED(PO1))    DEALLOCATE(PO1)
      IF(ALLOCATED(TO1))    DEALLOCATE(TO1)
      IF(ALLOCATED(RPO1))   DEALLOCATE(RPO1)
      IF(ALLOCATED(BS))     DEALLOCATE(BS)
      IF(ALLOCATED(BR))     DEALLOCATE(BR)
      IF(ALLOCATED(VM1))    DEALLOCATE(VM1)
      IF(ALLOCATED(PD))     DEALLOCATE(PD)
      IF(ALLOCATED(VTIN))   DEALLOCATE(VTIN)
      IF(ALLOCATED(PLIM))   DEALLOCATE(PLIM)
C --- BKMGRD ---
      IF(ALLOCATED(JSBLK))  DEALLOCATE(JSBLK)
      IF(ALLOCATED(IB1))    DEALLOCATE(IB1)
      IF(ALLOCATED(IB2))    DEALLOCATE(IB2)
      IF(ALLOCATED(KB1))    DEALLOCATE(KB1)
      IF(ALLOCATED(KB2))    DEALLOCATE(KB2)
      IF(ALLOCATED(JB1))    DEALLOCATE(JB1)
      IF(ALLOCATED(JB2))    DEALLOCATE(JB2)
C --- BKCNTL ---
      IF(ALLOCATED(PXTRAP)) DEALLOCATE(PXTRAP)
C --- BKSTAG ---
      IF(ALLOCATED(IND))    DEALLOCATE(IND)
      IF(ALLOCATED(INDLE))  DEALLOCATE(INDLE)
      IF(ALLOCATED(INDMIX)) DEALLOCATE(INDMIX)
      IF(ALLOCATED(NBLADE)) DEALLOCATE(NBLADE)
      IF(ALLOCATED(WRAD))   DEALLOCATE(WRAD)
      IF(ALLOCATED(PGUESS)) DEALLOCATE(PGUESS)
      IF(ALLOCATED(RATPIT)) DEALLOCATE(RATPIT)
      IF(ALLOCATED(NROW))   DEALLOCATE(NROW)
      IF(ALLOCATED(INDMID)) DEALLOCATE(INDMID)
      IF(ALLOCATED(INDTE))  DEALLOCATE(INDTE)
      IF(ALLOCATED(FACXDIF))DEALLOCATE(FACXDIF)
      IF(ALLOCATED(ALPHA_S))DEALLOCATE(ALPHA_S)
      IF(ALLOCATED(FPOLY))  DEALLOCATE(FPOLY)
      IF(ALLOCATED(UBLADE)) DEALLOCATE(UBLADE)
C --- BKTIP ---
      IF(ALLOCATED(KTIPS))  DEALLOCATE(KTIPS)
      IF(ALLOCATED(KTIPE))  DEALLOCATE(KTIPE)
      IF(ALLOCATED(FTHICK)) DEALLOCATE(FTHICK)
      IF(ALLOCATED(WHUB))   DEALLOCATE(WHUB)
      IF(ALLOCATED(WTIP))   DEALLOCATE(WTIP)
      IF(ALLOCATED(KS1))    DEALLOCATE(KS1)
      IF(ALLOCATED(KS2))    DEALLOCATE(KS2)
C --- BKDIFF ---
      IF(ALLOCATED(DRO))    DEALLOCATE(DRO)
      IF(ALLOCATED(DROE))   DEALLOCATE(DROE)
      IF(ALLOCATED(DROVX))  DEALLOCATE(DROVX)
      IF(ALLOCATED(DROVR))  DEALLOCATE(DROVR)
      IF(ALLOCATED(DRORVT)) DEALLOCATE(DRORVT)
C --- BKDIST ---
      IF(ALLOCATED(FTL))    DEALLOCATE(FTL)
      IF(ALLOCATED(FBL))    DEALLOCATE(FBL)
      IF(ALLOCATED(FTR))    DEALLOCATE(FTR)
      IF(ALLOCATED(FBR))    DEALLOCATE(FBR)
C --- BKSHROUD ---
      IF(ALLOCATED(AS))     DEALLOCATE(AS)
      IF(ALLOCATED(POAX))   DEALLOCATE(POAX)
      IF(ALLOCATED(TOAX))   DEALLOCATE(TOAX)
      IF(ALLOCATED(SHRDFLOW)) DEALLOCATE(SHRDFLOW)
      IF(ALLOCATED(HOAX))   DEALLOCATE(HOAX)
C --- BKSHRDFLUX ---
      IF(ALLOCATED(SHROUDGR)) DEALLOCATE(SHROUDGR)
      IF(ALLOCATED(SHROUDHO)) DEALLOCATE(SHROUDHO)
      IF(ALLOCATED(SHROUDVX)) DEALLOCATE(SHROUDVX)
      IF(ALLOCATED(SHROUDRVT)) DEALLOCATE(SHROUDRVT)
      IF(ALLOCATED(SHROUDVR)) DEALLOCATE(SHROUDVR)
C --- BKCOOL ---
      IF(ALLOCATED(CFLOWI1)) DEALLOCATE(CFLOWI1)
      IF(ALLOCATED(CFLOWIM)) DEALLOCATE(CFLOWIM)
      IF(ALLOCATED(CFLOWK1)) DEALLOCATE(CFLOWK1)
      IF(ALLOCATED(CFLOWKM)) DEALLOCATE(CFLOWKM)
      IF(ALLOCATED(VXCWLI1)) DEALLOCATE(VXCWLI1)
      IF(ALLOCATED(VXCWLIM)) DEALLOCATE(VXCWLIM)
      IF(ALLOCATED(VXCWLK1)) DEALLOCATE(VXCWLK1)
      IF(ALLOCATED(VXCWLKM)) DEALLOCATE(VXCWLKM)
      IF(ALLOCATED(VRCWLI1)) DEALLOCATE(VRCWLI1)
      IF(ALLOCATED(VRCWLIM)) DEALLOCATE(VRCWLIM)
      IF(ALLOCATED(VRCWLK1)) DEALLOCATE(VRCWLK1)
      IF(ALLOCATED(VRCWLKM)) DEALLOCATE(VRCWLKM)
      IF(ALLOCATED(HOCWLI1)) DEALLOCATE(HOCWLI1)
      IF(ALLOCATED(HOCWLIM)) DEALLOCATE(HOCWLIM)
      IF(ALLOCATED(HOCWLK1)) DEALLOCATE(HOCWLK1)
      IF(ALLOCATED(HOCWLKM)) DEALLOCATE(HOCWLKM)
      IF(ALLOCATED(RVTCWLI1)) DEALLOCATE(RVTCWLI1)
      IF(ALLOCATED(RVTCWLIM)) DEALLOCATE(RVTCWLIM)
      IF(ALLOCATED(RVTCWLK1)) DEALLOCATE(RVTCWLK1)
      IF(ALLOCATED(RVTCWLKM)) DEALLOCATE(RVTCWLKM)
      IF(ALLOCATED(SUMCWL)) DEALLOCATE(SUMCWL)
C --- BKATOT ---
      IF(ALLOCATED(ATOTK1)) DEALLOCATE(ATOTK1)
      IF(ALLOCATED(ATOTKM)) DEALLOCATE(ATOTKM)
      IF(ALLOCATED(ATOTI1)) DEALLOCATE(ATOTI1)
      IF(ALLOCATED(ATOTIM)) DEALLOCATE(ATOTIM)
C --- BKBLEED ---
      IF(ALLOCATED(BLFLOWI1)) DEALLOCATE(BLFLOWI1)
      IF(ALLOCATED(BLFLOWIM)) DEALLOCATE(BLFLOWIM)
      IF(ALLOCATED(BLFLOWK1)) DEALLOCATE(BLFLOWK1)
      IF(ALLOCATED(BLFLOWKM)) DEALLOCATE(BLFLOWKM)
      IF(ALLOCATED(SUMBLEED)) DEALLOCATE(SUMBLEED)
C --- BKOUT ---
      IF(ALLOCATED(PO_OUT_AVG)) DEALLOCATE(PO_OUT_AVG)
      IF(ALLOCATED(TO_OUT_AVG)) DEALLOCATE(TO_OUT_AVG)
      IF(ALLOCATED(YAW_OUT_AVG)) DEALLOCATE(YAW_OUT_AVG)
      IF(ALLOCATED(PITCH_OUT_AVG)) DEALLOCATE(PITCH_OUT_AVG)
      IF(ALLOCATED(VT_OUT_AVG)) DEALLOCATE(VT_OUT_AVG)
C --- BKNEWLOS ---
      IF(ALLOCATED(DIST_MIN)) DEALLOCATE(DIST_MIN)
      IF(ALLOCATED(XLENGTH)) DEALLOCATE(XLENGTH)
      IF(ALLOCATED(XLIMIT)) DEALLOCATE(XLIMIT)
      IF(ALLOCATED(VISC_LAM)) DEALLOCATE(VISC_LAM)
      IF(ALLOCATED(VISC_RAT)) DEALLOCATE(VISC_RAT)
      IF(ALLOCATED(FST_RAT)) DEALLOCATE(FST_RAT)
      IF(ALLOCATED(Y_PLUS)) DEALLOCATE(Y_PLUS)
      IF(ALLOCATED(YPLUS_K1)) DEALLOCATE(YPLUS_K1)
      IF(ALLOCATED(YPLUS_KM)) DEALLOCATE(YPLUS_KM)
      IF(ALLOCATED(YPLUS_I1)) DEALLOCATE(YPLUS_I1)
      IF(ALLOCATED(YPLUS_IM)) DEALLOCATE(YPLUS_IM)
C --- BKSPALOS ---
      IF(ALLOCATED(TRANS_KVIS)) DEALLOCATE(TRANS_KVIS)
      IF(ALLOCATED(TRANS_DYN_VIS)) DEALLOCATE(TRANS_DYN_VIS)
      IF(ALLOCATED(DYN_VIS_ML)) DEALLOCATE(DYN_VIS_ML)
      IF(ALLOCATED(TRANS_VORT)) DEALLOCATE(TRANS_VORT)
      IF(ALLOCATED(DEL_DYNVIS)) DEALLOCATE(DEL_DYNVIS)
      IF(ALLOCATED(ROAVG_CELL)) DEALLOCATE(ROAVG_CELL)
      IF(ALLOCATED(ABS_VORT)) DEALLOCATE(ABS_VORT)
      IF(ALLOCATED(GRAD_TVIS)) DEALLOCATE(GRAD_TVIS)
      IF(ALLOCATED(T_SOURCE)) DEALLOCATE(T_SOURCE)
      IF(ALLOCATED(DWALLSQ)) DEALLOCATE(DWALLSQ)
      IF(ALLOCATED(TVISGRADX)) DEALLOCATE(TVISGRADX)
      IF(ALLOCATED(TVISGRADR)) DEALLOCATE(TVISGRADR)
      IF(ALLOCATED(TVISGRADT)) DEALLOCATE(TVISGRADT)
      IF(ALLOCATED(VISC_TURB)) DEALLOCATE(VISC_TURB)
      IF(ALLOCATED(SPAREVAR)) DEALLOCATE(SPAREVAR)
C --- BKTFLOW ---
      IF(ALLOCATED(AVGPBLADE)) DEALLOCATE(AVGPBLADE)
      IF(ALLOCATED(PBLADE))  DEALLOCATE(PBLADE)
      IF(ALLOCATED(ROVAR_M1)) DEALLOCATE(ROVAR_M1)
      IF(ALLOCATED(BFORCE_X)) DEALLOCATE(BFORCE_X)
      IF(ALLOCATED(BFORCE_R)) DEALLOCATE(BFORCE_R)
      IF(ALLOCATED(BFORCE_T)) DEALLOCATE(BFORCE_T)
      IF(ALLOCATED(BFORCE_Q)) DEALLOCATE(BFORCE_Q)
      IF(ALLOCATED(SFACPB))  DEALLOCATE(SFACPB)
      IF(ALLOCATED(DEVN_ANGL)) DEALLOCATE(DEVN_ANGL)
      IF(ALLOCATED(EXIT_ANGL)) DEALLOCATE(EXIT_ANGL)
      IF(ALLOCATED(FRAC_SPAN)) DEALLOCATE(FRAC_SPAN)
      IF(ALLOCATED(EXANG))   DEALLOCATE(EXANG)
      IF(ALLOCATED(ALPHA_CENT)) DEALLOCATE(ALPHA_CENT)
      IF(ALLOCATED(CENT_ANGL)) DEALLOCATE(CENT_ANGL)
      IF(ALLOCATED(S_DIST))  DEALLOCATE(S_DIST)
C --- BKINVERSE ---
      IF(ALLOCATED(PSPEC_I1)) DEALLOCATE(PSPEC_I1)
      IF(ALLOCATED(PSPEC_IM)) DEALLOCATE(PSPEC_IM)
      IF(ALLOCATED(SDIST))   DEALLOCATE(SDIST)
      IF(ALLOCATED(YMOVE_I1)) DEALLOCATE(YMOVE_I1)
      IF(ALLOCATED(YMOVE_IM)) DEALLOCATE(YMOVE_IM)
      IF(ALLOCATED(SUM_SOURCE_I1)) DEALLOCATE(SUM_SOURCE_I1)
      IF(ALLOCATED(SUM_SOURCE_IM)) DEALLOCATE(SUM_SOURCE_IM)
      IF(ALLOCATED(TKLIM))   DEALLOCATE(TKLIM)
      IF(ALLOCATED(ABT_MID)) DEALLOCATE(ABT_MID)
      IF(ALLOCATED(FRAC_ABT)) DEALLOCATE(FRAC_ABT)
      IF(ALLOCATED(S_MERID)) DEALLOCATE(S_MERID)
      IF(ALLOCATED(PDIV))    DEALLOCATE(PDIV)
      IF(ALLOCATED(P_AVGG))  DEALLOCATE(P_AVGG)
      IF(ALLOCATED(SUM_MOVE_I1)) DEALLOCATE(SUM_MOVE_I1)
      IF(ALLOCATED(SUM_MOVE_IM)) DEALLOCATE(SUM_MOVE_IM)
      IF(ALLOCATED(FRAC_CRD)) DEALLOCATE(FRAC_CRD)
      IF(ALLOCATED(RT_MID))  DEALLOCATE(RT_MID)
      IF(ALLOCATED(FSOURCE)) DEALLOCATE(FSOURCE)
      IF(ALLOCATED(DY_ROTN)) DEALLOCATE(DY_ROTN)
      IF(ALLOCATED(TK_SURF)) DEALLOCATE(TK_SURF)
      IF(ALLOCATED(TKORIG))  DEALLOCATE(TKORIG)
      IF(ALLOCATED(SURF_FLUX)) DEALLOCATE(SURF_FLUX)
      IF(ALLOCATED(TKLIN))   DEALLOCATE(TKLIN)
      IF(ALLOCATED(TKSET))   DEALLOCATE(TKSET)
      IF(ALLOCATED(TKMIN))   DEALLOCATE(TKMIN)
      IF(ALLOCATED(TK_DIFF)) DEALLOCATE(TK_DIFF)
      IF(ALLOCATED(ROVMER))  DEALLOCATE(ROVMER)
C --- BKTABLES ---
      IF(ALLOCATED(RGAS_NOW)) DEALLOCATE(RGAS_NOW)
      IF(ALLOCATED(PHEXP))   DEALLOCATE(PHEXP)
      IF(ALLOCATED(GA_PV))   DEALLOCATE(GA_PV)
      IF(ALLOCATED(WET))     DEALLOCATE(WET)
      IF(ALLOCATED(H_TO_T))  DEALLOCATE(H_TO_T)
      IF(ALLOCATED(ENTPY))   DEALLOCATE(ENTPY)
      IF(ALLOCATED(UINT))    DEALLOCATE(UINT)
C --- BLKTAB ---
      IF(ALLOCATED(HO_INN))  DEALLOCATE(HO_INN)
      IF(ALLOCATED(ROSTAG_IN)) DEALLOCATE(ROSTAG_IN)
C --- BKSTRESS ---
      IF(ALLOCATED(TXX))    DEALLOCATE(TXX)
      IF(ALLOCATED(TXR))    DEALLOCATE(TXR)
      IF(ALLOCATED(TXT))    DEALLOCATE(TXT)
      IF(ALLOCATED(TRX))    DEALLOCATE(TRX)
      IF(ALLOCATED(TRR))    DEALLOCATE(TRR)
      IF(ALLOCATED(TRT))    DEALLOCATE(TRT)
      IF(ALLOCATED(TTX))    DEALLOCATE(TTX)
      IF(ALLOCATED(TTR))    DEALLOCATE(TTR)
      IF(ALLOCATED(TTT))    DEALLOCATE(TTT)
      IF(ALLOCATED(QXX))    DEALLOCATE(QXX)
      IF(ALLOCATED(QRR))    DEALLOCATE(QRR)
      IF(ALLOCATED(QTT))    DEALLOCATE(QTT)
C
      IALLOC_STATE = 0
      RETURN
      END SUBROUTINE DEALLOC_MULTALL_DATA
C
      END MODULE MULTALL_DATA
